package entity;
// Generated 2014-10-18 21:27:43 by Hibernate Tools 4.3.1



/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private Integer odId;
     private Products product;
     private Float unitPrice;
     private Short quantity;
     private Float discount;

    public OrderDetails() {
    }

    public OrderDetails(Products product, Float unitPrice, Short quantity, Float discount) {
       this.product = product;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.discount = discount;
    }
   
    public Integer getOdId() {
        return this.odId;
    }
    
    public void setOdId(Integer odId) {
        this.odId = odId;
    }
    public Products getProduct() {
        return product;
    }

    public void setProduct(Products product) {
        this.product = product;
    }
    public Float getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }
    public Float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Float discount) {
        this.discount = discount;
    }




}


